#spring.application.name=employee_management

server:
  port: ${SERVER_PORT}

spring:
  config:
    import: optional:file:.env[.properties]


  application:
    name: employee_management
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#JWT Config
auth:
  token:
    expirationInMils: 3600000
    jwtSecret: ${JWT_SECRET}
